services:
  mysqldb:
    image: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DOCKER_MYSQLDB_PASSWORD
      MYSQL_DATABASE: $DOCKER_MYSQLDB_NAME
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redisdb:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: $DOCKER_REDIS_HOST
    depends_on:
      mysqldb:
        condition: service_healthy
      redisdb:
        condition: service_started
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis-data:
